version: 1
project_name: karpenter-generate

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/punkwalker/karpenter-generate/cmd.version={{ .Version }} -X github.com/punkwalker/karpenter-generate/cmd.commit={{ .ShortCommit }} -X github.com/punkwalker/karpenter-generate/cmd.date={{ .Date }}
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
brews:
  - repository:
      owner: punkwalker
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/punkwalker/karpenter-generate
    description: A simple CLI tool to generate Karpenter CRDs from EKS Managed Node Groups
    license: MIT-0
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^workflow:"