name: ci

on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # So golangci-lint can do git diff HEAD~1

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Build
        run: make build

      - name: Smoke Test
        run: ./karpenter-generate version